test

diff --git a/codebundles/k8s-fluxcd-helm-health/meta.yaml b/codebundles/k8s-fluxcd-helm-health/meta.yaml
--- a/codebundles/k8s-fluxcd-helm-health/meta.yaml
+++ b/codebundles/k8s-fluxcd-helm-health/meta.yaml
@@ -8,10 +8,25 @@ commands:
   explanation: This command is used to retrieve information about a specific Kubernetes
     resource within a specified namespace and context. The resource name, namespace,
     and context are all specified using the respective placeholders.
-  multi_line_details: "```bash\n# Command to get resource with a specific name and\
-    \ namespace using kubectl\n# Get the resource from a specific context\n\nkubectl\
-    \ get \\\n  ${RESOURCE_NAME} \\\n  -n ${NAMESPACE} \\\n  --context ${CONTEXT}\n\
-    ```"
+  multi_line_details: '#!/bin/bash
+
+
+    # This script retrieves information about a specific resource in a Kubernetes
+    cluster
+
+    # by using the specified resource name, namespace, and context.
+
+
+    RESOURCE_NAME="your_resource_name"
+
+    NAMESPACE="your_namespace"
+
+    CONTEXT="your_context"
+
+
+    # Use kubectl to get the specified resource in the specified namespace and context
+
+    kubectl get $RESOURCE_NAME -n $NAMESPACE --context $CONTEXT'
   name: list_all_available_fluxcd_helmreleases_in_namespace_namespace
 - command: 'kubectl get ${RESOURCE_NAME} -n ${NAMESPACE} -o=jsonpath="{range .items[*]}{''\nName:
     ''}{@.metadata.name}{''\nlastAppliedRevision:''}{@.status.lastAppliedRevision}{''\nlastAttemptedRevision:''}{@.status.lastAttemptedRevision}{''\n---''}{end}"
@@ -26,14 +41,16 @@ commands:
   explanation: This command retrieves specific resource information from a specified
     namespace in your Kubernetes cluster and formats the output in a specific JSON
     format. If the command fails, it will return a success status.
-  multi_line_details: "```bash\n#!/bin/bash\n\n# This command fetches the resource\
-    \ name, last applied revision, and last attempted revision for a specific namespace\
-    \ using kubectl.\n\nkubectl get ${RESOURCE_NAME} \\ # Get the specified resource\n\
-    \  -n ${NAMESPACE} \\ # in the specified namespace\n  -o=jsonpath=\"{range .items[*]}{'\\\
-    nName: '}{@.metadata.name}{'\\nlastAppliedRevision:'}{@.status.lastAppliedRevision}{'\\\
-    nlastAttemptedRevision:'}{@.status.lastAttemptedRevision}{'\\n---'}{end}\" \\\
-    \ # output in custom format\n  --context ${CONTEXT} || true # switch to the specified\
-    \ context or return true if unsuccessful\n```"
+  multi_line_details: '#!/bin/bash
+
+
+    # Get resource with specific name in a namespace in JSON format using kubectl
+
+    # and extract specific fields, then print them with custom formatting.
+
+    kubectl get ${RESOURCE_NAME} -n ${NAMESPACE} -o=jsonpath="{range .items[*]}{''\nName:
+    ''}{@.metadata.name}{''\nlastAppliedRevision:''}{@.status.lastAppliedRevision}{''\nlastAttemptedRevision:''}{@.status.lastAttemptedRevision}{''\n---''}{end}"
+    --context ${CONTEXT} || true'
   name: fetch_installed_fluxcd_helmrelease_versions_in_namespace_namespace
 - command: 'kubectl get ${RESOURCE_NAME} -n ${NAMESPACE} -o json --context ${CONTEXT}
     | jq -r ''.items[] | select(.status.lastAppliedRevision!=.status.lastAttemptedRevision)
@@ -46,42 +63,29 @@ commands:
     resource in a particular namespace, using the specified context. It then processes
     the output using `jq` to filter and format it, displaying the resource's name,
     last attempted version, and last applied revision if they are different.
-  multi_line_details: '```bash
-
-    #!/bin/bash
+  multi_line_details: '#!/bin/bash
 
 
-    # set the resource name
-
-    RESOURCE_NAME="deployment"
-
-
-    # set the namespace
-
-    NAMESPACE="example-namespace"
+    # This script retrieves the specified Kubernetes resource in JSON format, filters
+    and extracts relevant information using jq, and displays it in a custom format.
 
 
-    # set the context
+    # Define variables
 
-    CONTEXT="example-context"
+    RESOURCE_NAME="..."  # Specify the resource name
 
+    NAMESPACE="..."      # Specify the namespace
 
-    # get the json output of the specified resource in the specified namespace and
-    context
-
-    json_output=$(kubectl get ${RESOURCE_NAME} -n ${NAMESPACE} -o json --context ${CONTEXT})
+    CONTEXT="..."        # Specify the context
 
 
-    # use jq to filter and format the json output
+    # Retrieve the resource in JSON format and process using jq
 
-    filtered_output=$(echo ${json_output} | jq -r ''.items[] | select(.status.lastAppliedRevision!=.status.lastAttemptedRevision)
+    kubectl get ${RESOURCE_NAME} -n ${NAMESPACE} -o json --context ${CONTEXT} | \
+
+    jq -r ''.items[] | select(.status.lastAppliedRevision!=.status.lastAttemptedRevision)
     | "Name: " + .metadata.name + " Last Attempted Version: " + .status.lastAttemptedRevision
-    + " Last Applied Revision: " + .status.lastAppliedRevision'')
-
-
-    echo $filtered_output
-
-    ```'
+    + " Last Applied Revision: " + .status.lastAppliedRevision'''
   name: fetch_mismatched_fluxcd_helmrelease_version_in_namespace_namespace
 - command: 'kubectl get ${RESOURCE_NAME} -n ${NAMESPACE} -o=jsonpath="{range .items[?(@.status.conditions[].status==''False'')]}{''-----\nName:
     ''}{@.metadata.name}{''\n''}{@.status.conditions[*].message}{''\n''}{end}" --context
@@ -98,13 +102,15 @@ commands:
     messages of any items with a condition status of 'False,' while also displaying
     a line of dashes before each item. If no items meet the criteria, it will return
     true.
-  multi_line_details: "```\n# This command uses kubectl to get specific resource in\
-    \ a namespace and print out its name and status message if the status condition\
-    \ is false\n# It uses jsonpath to format the output\n# --context flag specifies\
-    \ the Kubernetes context to use\n\nkubectl get ${RESOURCE_NAME} \\\n  -n ${NAMESPACE}\
-    \ \\\n  -o=jsonpath=\"{range .items[?(@.status.conditions[].status=='False')]}{'-----\\\
+  multi_line_details: "#!/bin/bash\n\n# This command retrieves the resource named\
+    \ ${RESOURCE_NAME} in the specified namespace ${NAMESPACE}\n# It then uses jsonpath\
+    \ to filter and format the output to display the names and status messages for\
+    \ items \n# with status conditions set to 'False'\n# The --context flag specifies\
+    \ the name of the kubeconfig context to use\n# If the kubectl get command fails,\
+    \ it will return a zero exit status (true)\n\nkubectl get ${RESOURCE_NAME} -n\
+    \ ${NAMESPACE} \\\n-o=jsonpath=\"{range .items[?(@.status.conditions[].status=='False')]}{'-----\\\
     nName: '}{@.metadata.name}{'\\n'}{@.status.conditions[*].message}{'\\n'}{end}\"\
-    \ \\\n  --context ${CONTEXT} \\\n  || true\n```"
+    \ \\\n--context ${CONTEXT} || true"
   name: fetch_fluxcd_helmrelease_error_messages_in_namespace_namespace
 - command: 'namespace="${NAMESPACE}" context="${CONTEXT}"; helm_releases=$(kubectl
     get ${RESOURCE_NAME} -n "$namespace" --context "$context" -o json | jq -r ''.items[]
@@ -141,49 +147,42 @@ commands:
     about Helm releases in a given namespace and context. It then checks for available
     updates for each release's associated chart from a Helm repository and reports
     the results.
-  multi_line_details: "```bash\n#!/bin/bash\n\n# Set namespace and context variables\n\
-    namespace=\"${NAMESPACE}\"\ncontext=\"${CONTEXT}\"\n\n# Get list of Helm releases\n\
-    helm_releases=$(kubectl get ${RESOURCE_NAME} -n \"$namespace\" --context \"$context\"\
-    \ -o json | jq -r '.items[] | .metadata.name')\n\n# Iterate over helm releases\n\
-    echo \"$helm_releases\" | while IFS= read -r release; do \n    # Get chart details\
-    \ for each release\n    chart_details=$(kubectl get ${RESOURCE_NAME} \"$release\"\
+  multi_line_details: "namespace=\"${NAMESPACE}\" \ncontext=\"${CONTEXT}\" \n\n# Get\
+    \ the names of all Helm releases\nhelm_releases=$(kubectl get ${RESOURCE_NAME}\
+    \ -n \"$namespace\" --context \"$context\" -o json | jq -r '.items[] | .metadata.name')\
+    \ \n\n# Iterate through each Helm release\necho \"$helm_releases\" | while IFS=\
+    \ read -r release; do \n    chart_details=$(kubectl get ${RESOURCE_NAME} \"$release\"\
     \ -n \"$namespace\" --context \"$context\" -o json | jq -r '.spec.chart.spec //\
-    \ empty')\n    \n    # Check if chart details are available\n    if [[ -n \"$chart_details\"\
-    \ ]]; then \n        # Extract chart attributes from chart details\n        chart_kind=$(echo\
-    \ \"$chart_details\" | jq -r '.sourceRef.kind // empty')\n        chart_name=$(echo\
-    \ \"$chart_details\" | jq -r '.chart // empty')\n        chart_source_name=$(echo\
-    \ \"$chart_details\" | jq -r '.sourceRef.name // empty')\n        chart_namespace=$(echo\
-    \ \"$chart_details\" | jq -r '.sourceRef.namespace // empty')\n        chart_version=$(echo\
-    \ \"$chart_details\" | jq -r '.version // \"N/A\"')\n        \n        # Check\
-    \ if chart kind is HelmRepository and required attributes are present\n      \
-    \  if [[ \"$chart_kind\" == \"HelmRepository\" && -n \"$chart_name\" && -n \"\
-    $chart_namespace\" ]]; then \n            # Get repository URL for the chart\n\
-    \            repo_url=$(kubectl get helmrepositories.source.toolkit.fluxcd.io\
+    \ empty'); \n\n    # Check if the chart details are available\n    if [[ -n \"\
+    $chart_details\" ]]; then \n        chart_kind=$(echo \"$chart_details\" | jq\
+    \ -r '.sourceRef.kind // empty'); \n        chart_name=$(echo \"$chart_details\"\
+    \ | jq -r '.chart // empty'); \n        chart_source_name=$(echo \"$chart_details\"\
+    \ | jq -r '.sourceRef.name // empty'); \n        chart_namespace=$(echo \"$chart_details\"\
+    \ | jq -r '.sourceRef.namespace // empty'); \n        chart_version=$(echo \"\
+    $chart_details\" | jq -r '.version // \"N/A\"'); \n\n        # Check if the chart\
+    \ belongs to a HelmRepository and has necessary details\n        if [[ \"$chart_kind\"\
+    \ == \"HelmRepository\" && -n \"$chart_name\" && -n \"$chart_namespace\" ]]; then\
+    \ \n            repo_url=$(kubectl get helmrepositories.source.toolkit.fluxcd.io\
     \ \"$chart_source_name\" -n \"$chart_namespace\" --context \"$context\" -o json\
-    \ | jq -r '.spec.url // empty')\n            \n            # Check if repository\
+    \ | jq -r '.spec.url // empty'); \n    \n            # Check if the repository\
     \ URL is available\n            if [[ -n \"$repo_url\" ]]; then \n           \
-    \     temp_repo_name=\"$chart_source_name-temp-$release\"\n                \n\
-    \                # Add temporary repository for the chart\n                add_repo=$(helm\
-    \ repo add \"$temp_repo_name\" \"$repo_url\")\n                \n            \
-    \    # Search available versions of the chart in the repository\n            \
-    \    available_chart_version=$(helm search repo \"$temp_repo_name\"/\"$chart_name\"\
-    \ --version \">$chart_version\" --output json | jq -r '.[].version')\n       \
-    \         \n                # Check if available chart version is found\n    \
-    \            if [[ -n \"$available_chart_version\" ]]; then \n               \
-    \     sorted_versions=($(echo \"\\${available_chart_version[@]}\" | tr ' ' '\\\
-    n' | sort -V))\n                    available_version=\\${sorted_versions[-1]}\n\
-    \                    version_update_available=\"True\"\n                else \n\
-    \                    available_version=\"N/A\"\n                    version_update_available=\"\
-    False\"\n                fi\n                \n                # Remove temporary\
-    \ repository\n                remove_repo=$(helm repo remove \"$temp_repo_name\"\
-    )\n                \n            else \n                available_version=\"N/A\"\
-    \n                version_update_available=\"False\"\n            fi\n       \
-    \     \n        else \n            available_version=\"N/A\"\n            version_update_available=\"\
-    False\"\n        fi\n        \n    else \n        chart_name=\"N/A\"\n       \
-    \ chart_namespace=\"N/A\"\n        chart_version=\"N/A\"\n        available_version=\"\
-    N/A\"\n        version_update_available=\"False\"\n    fi\n    \n    # Print chart\
-    \ details and availability information\n    echo \"Release: $release | Chart:\
-    \ $chart_namespace/$chart_name | Installed Version: $chart_version | Available\
-    \ Update: $version_update_available | Available Version: $available_version\"\n\
-    done \n```"
+    \     temp_repo_name=\"$chart_source_name-temp-$release\"; \n                add_repo=$(helm\
+    \ repo add \"$temp_repo_name\" \"$repo_url\"); \n                available_chart_version=$(helm\
+    \ search repo \"$temp_repo_name\"/\"$chart_name\" --version \">$chart_version\"\
+    \ --output json | jq -r '.[].version'); \n\n                # Check if an available\
+    \ chart version is found\n                if [[ -n \"$available_chart_version\"\
+    \ ]]; then \n                    sorted_versions=($(echo \"${available_chart_version[@]}\"\
+    \ | tr ' ' '\\n' | sort -V)); \n                    available_version=${sorted_versions[-1]};\
+    \ \n                    version_update_available=\"True\"; \n                else\
+    \ \n                    available_version=\"N/A\"; \n                    version_update_available=\"\
+    False\"; \n                fi; \n                remove_repo=$(helm repo remove\
+    \ \"$temp_repo_name\"); \n            else \n                available_version=\"\
+    N/A\"; \n                version_update_available=\"False\"; \n            fi;\
+    \ \n        else \n            available_version=\"N/A\"; \n            version_update_available=\"\
+    False\"; \n        fi; \n    else \n        chart_name=\"N/A\"; \n        chart_namespace=\"\
+    N/A\"; \n        chart_version=\"N/A\"; \n        available_version=\"N/A\"; \n\
+    \        version_update_available=\"False\"; \n    fi; \n    echo \"Release: $release\
+    \ | Chart: $chart_namespace/$chart_name | Installed Version: $chart_version |\
+    \ Available Update: $version_update_available | Available Version: $available_version\"\
+    ; \ndone"
   name: check_for_available_helm_chart_updates_in_namespace_namespace
diff --git a/codebundles/k8s-prometheus-healthcheck/meta.yaml b/codebundles/k8s-prometheus-healthcheck/meta.yaml
--- a/codebundles/k8s-prometheus-healthcheck/meta.yaml
+++ b/codebundles/k8s-prometheus-healthcheck/meta.yaml
@@ -12,37 +12,30 @@ commands:
   explanation: This command retrieves the logs from a specific pod running in a Kubernetes
     cluster and searches for any lines containing the phrase "load failure", ignoring
     case. If no matches are found, it returns a status of true.
-  multi_line_details: '```bash
+  multi_line_details: '#!/bin/bash
 
-    #!/bin/bash
-
-    # kubectl command to retrieve logs from a specific pod in a Kubernetes cluster
-
-
-    # Set the context and namespace for the kubectl commands
-
-    CONTEXT=${CONTEXT}
-
-    PROM_NAMESPACE=${PROM_NAMESPACE}
+    # This script retrieves logs from Prometheus pod in the specified namespace and
+    checks for any failed loads
 
 
-    # Get the name of the Prometheus pod
+    # Set the kubectl context and namespace
 
-    PROM_POD=$(kubectl --context=${CONTEXT} -n ${PROM_NAMESPACE} get pods -l app.kubernetes.io/name=prometheus
-    -o=jsonpath=''{.items[0].metadata.name}'')
+    CONTEXT="example-context"
+
+    PROM_NAMESPACE="example-namespace"
 
 
-    # Get the logs from the Prometheus container within the specified pod and filter
-    for lines containing "load" and "fail"
+    # Get the name of the Prometheus pod using a label selector
 
-    kubectl --context=${CONTEXT} -n ${PROM_NAMESPACE} logs ${PROM_POD} -c prometheus
-    | grep -iP "(load.*.fail)" || true
+    PROM_POD_NAME=$(kubectl --context=${CONTEXT} -n ${PROM_NAMESPACE} get pods -l
+    app.kubernetes.io/name=prometheus -o=jsonpath=''{.items[0].metadata.name}'')
 
-    ```
 
-    This multi-line script breaks down the original one-liner kubectl command into
-    separate steps with comments explaining each part and uses variables for the context
-    and namespace to make it more readable and maintainable.'
+    # Retrieve the logs from the Prometheus pod for the ''prometheus'' container and
+    filter for the specified pattern
+
+    kubectl --context=${CONTEXT} -n ${PROM_NAMESPACE} logs ${PROM_POD_NAME} -c prometheus
+    | grep -iP "(load.*.fail)" || true'
   name: check_for_successful_rule_setup
 - command: kubectl get clusterrole/kube-prometheus-stack-operator -ojson
   doc_links: '
@@ -56,14 +49,9 @@ commands:
     role named kube-prometheus-stack-operator in JSON format. It's a way to inspect
     the permissions and access control settings for this specific role in a Kubernetes
     cluster.
-  multi_line_details: '```
-
-    # Retrieve the cluster role resource named kube-prometheus-stack-operator in JSON
-    format
-
-    kubectl get clusterrole/kube-prometheus-stack-operator -o json
-
-    ```'
+  multi_line_details: "#!/bin/bash\n\n# This command is used to get the details of\
+    \ the cluster role\n# kube-prometheus-stack-operator in JSON format using kubectl\n\
+    \nkubectl get clusterrole/kube-prometheus-stack-operator \\\n  -ojson"
   name: verify_prometheus_rbac_can_access_servicemonitors
 - command: kubectl --context=${CONTEXT} -n ${PROM_NAMESPACE} logs $(kubectl --context=${CONTEXT}
     -n ${PROM_NAMESPACE} get pods -l app.kubernetes.io/name=prometheus -o=jsonpath='{.items[0].metadata.name}')
@@ -79,25 +67,26 @@ commands:
     Kubernetes cluster, and then uses grep to search for any lines containing the
     phrase "scrape error," ignoring case. If no errors are found, the command returns
     a status of "true."
-  multi_line_details: '```
+  multi_line_details: '```bash
 
-    # Set the kubectl context and namespace
+    # Set the kubectl context and namespace as variables
 
-    context=${CONTEXT}
+    CONTEXT=${CONTEXT}
 
-    namespace=${PROM_NAMESPACE}
+    PROM_NAMESPACE=${PROM_NAMESPACE}
 
 
-    # Get the pod name for the prometheus application
+    # Get the name of the pod running Prometheus using the specified context and namespace
 
-    pod_name=$(kubectl --context=${context} -n ${namespace} get pods -l app.kubernetes.io/name=prometheus
+    PROM_POD=$(kubectl --context=${CONTEXT} -n ${PROM_NAMESPACE} get pods -l app.kubernetes.io/name=prometheus
     -o=jsonpath=''{.items[0].metadata.name}'')
 
 
-    # Get the prometheus logs from the specified pod and filter by ''scrape.*.error''
+    # Get the logs from the Prometheus pod and search for any lines containing "scrape"
+    and "error", case-insensitive, then return true if not found
 
-    kubectl --context=${context} -n ${namespace} logs ${pod_name} -c prometheus |
-    grep -iP "(scrape.*.error)" || true
+    kubectl --context=${CONTEXT} -n ${PROM_NAMESPACE} logs $PROM_POD -c prometheus
+    | grep -iP "(scrape.*.error)" || true
 
     ```'
   name: identify_endpoint_scraping_errors
@@ -120,24 +109,26 @@ commands:
     HTTP status code.
   multi_line_details: '```
 
-    # Set the Kubernetes context and namespace
-
-    context=${CONTEXT}
-
-    namespace=${PROM_NAMESPACE}
+    #!/bin/bash
 
 
-    # Get the name of the Prometheus pod
+    # Set the kubectl context and namespace
 
-    prom_pod=$(kubectl --context=${context} -n ${namespace} get pods -l app.kubernetes.io/name=prometheus
+    CONTEXT=my-context
+
+    PROM_NAMESPACE=my-namespace
+
+
+    # Get the name of the prometheus pod
+
+    PROM_POD=$(kubectl --context=${CONTEXT} -n ${PROM_NAMESPACE} get pods -l app.kubernetes.io/name=prometheus
     -o=jsonpath=''{.items[0].metadata.name}'')
 
 
-    # Execute a command in the Prometheus pod to check its health
+    # Exec into the prometheus container and run the wget command to check health
 
-    health_status=$(kubectl --context=${context} -n ${namespace} exec ${prom_pod}
-    --container prometheus -- wget -qO- -S 127.0.0.1:9090/-/healthy 2>&1 | grep "HTTP/"
-    | awk ''{print $2}'')
+    kubectl --context=${CONTEXT} -n ${PROM_NAMESPACE} exec $PROM_POD --container prometheus
+    -- wget -qO- -S 127.0.0.1:9090/-/healthy 2>&1 | grep "HTTP/" | awk ''{print $2}''
 
     ```'
   name: check_prometheus_api_healthy
